/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// AccountSourceResponseDto
    /// </summary>
    [DataContract(Name = "AccountSourceResponseDto")]
    public partial class AccountSourceResponseDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SourceType
        /// </summary>
        [DataMember(Name = "sourceType", IsRequired = true, EmitDefaultValue = true)]
        public AccountSourceTypeEnum SourceType { get; set; }

        /// <summary>
        /// Gets or Sets CreationMethod
        /// </summary>
        [DataMember(Name = "creationMethod", IsRequired = true, EmitDefaultValue = true)]
        public AccountSourceCreationMethodEnum CreationMethod { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSourceResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountSourceResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSourceResponseDto" /> class.
        /// </summary>
        /// <param name="id">Account source ID (required).</param>
        /// <param name="userId">User ID (required).</param>
        /// <param name="originProjectId">Origin project ID (required).</param>
        /// <param name="sourceType">sourceType (required).</param>
        /// <param name="creationMethod">creationMethod (required).</param>
        /// <param name="turnkeyResourceId">Turnkey resource ID (HD wallet ID or private key ID) (required).</param>
        /// <param name="displayName">User-defined display name.</param>
        public AccountSourceResponseDto(string id = default(string), string userId = default(string), string originProjectId = default(string), AccountSourceTypeEnum sourceType = default(AccountSourceTypeEnum), AccountSourceCreationMethodEnum creationMethod = default(AccountSourceCreationMethodEnum), string turnkeyResourceId = default(string), string displayName = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for AccountSourceResponseDto and cannot be null");
            }
            this.Id = id;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for AccountSourceResponseDto and cannot be null");
            }
            this.UserId = userId;
            // to ensure "originProjectId" is required (not null)
            if (originProjectId == null)
            {
                throw new ArgumentNullException("originProjectId is a required property for AccountSourceResponseDto and cannot be null");
            }
            this.OriginProjectId = originProjectId;
            this.SourceType = sourceType;
            this.CreationMethod = creationMethod;
            // to ensure "turnkeyResourceId" is required (not null)
            if (turnkeyResourceId == null)
            {
                throw new ArgumentNullException("turnkeyResourceId is a required property for AccountSourceResponseDto and cannot be null");
            }
            this.TurnkeyResourceId = turnkeyResourceId;
            this.DisplayName = displayName;
        }

        /// <summary>
        /// Account source ID
        /// </summary>
        /// <value>Account source ID</value>
        /*
        <example>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// User ID
        /// </summary>
        /// <value>User ID</value>
        /*
        <example>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</example>
        */
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Origin project ID
        /// </summary>
        /// <value>Origin project ID</value>
        /*
        <example>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</example>
        */
        [DataMember(Name = "originProjectId", IsRequired = true, EmitDefaultValue = true)]
        public string OriginProjectId { get; set; }

        /// <summary>
        /// Turnkey resource ID (HD wallet ID or private key ID)
        /// </summary>
        /// <value>Turnkey resource ID (HD wallet ID or private key ID)</value>
        /*
        <example>tk_abc123...</example>
        */
        [DataMember(Name = "turnkeyResourceId", IsRequired = true, EmitDefaultValue = true)]
        public string TurnkeyResourceId { get; set; }

        /// <summary>
        /// User-defined display name
        /// </summary>
        /// <value>User-defined display name</value>
        /*
        <example>My Main Account</example>
        */
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountSourceResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  OriginProjectId: ").Append(OriginProjectId).Append("\n");
            sb.Append("  SourceType: ").Append(SourceType).Append("\n");
            sb.Append("  CreationMethod: ").Append(CreationMethod).Append("\n");
            sb.Append("  TurnkeyResourceId: ").Append(TurnkeyResourceId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
