/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// Account source type
    /// </summary>
    /// <value>Account source type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum AccountSourceTypeEnum
    {
        /// <summary>
        /// Enum RecoveryPhrase for value: recovery-phrase
        /// </summary>
        [EnumMember(Value = "recovery-phrase")]
        RecoveryPhrase = 1,

        /// <summary>
        /// Enum PrivateKey for value: private-key
        /// </summary>
        [EnumMember(Value = "private-key")]
        PrivateKey = 2
    }

}
