/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// BitcoinSignTransactionResponseDto
    /// </summary>
    [DataContract(Name = "BitcoinSignTransactionResponseDto")]
    internal partial class BitcoinSignTransactionResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BitcoinSignTransactionResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BitcoinSignTransactionResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BitcoinSignTransactionResponseDto" /> class.
        /// </summary>
        /// <param name="signedTransaction">The signed Bitcoin transaction (hex-encoded, ready for broadcasting) (required).</param>
        public BitcoinSignTransactionResponseDto(string signedTransaction = default(string))
        {
            // to ensure "signedTransaction" is required (not null)
            if (signedTransaction == null)
            {
                throw new ArgumentNullException("signedTransaction is a required property for BitcoinSignTransactionResponseDto and cannot be null");
            }
            this.SignedTransaction = signedTransaction;
        }

        /// <summary>
        /// The signed Bitcoin transaction (hex-encoded, ready for broadcasting)
        /// </summary>
        /// <value>The signed Bitcoin transaction (hex-encoded, ready for broadcasting)</value>
        /*
        <example>02000000000101abcd...</example>
        */
        [DataMember(Name = "signedTransaction", IsRequired = true, EmitDefaultValue = true)]
        public string SignedTransaction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BitcoinSignTransactionResponseDto {\n");
            sb.Append("  SignedTransaction: ").Append(SignedTransaction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
