/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// Bitcoin address type (only for bitcoin chain)
    /// </summary>
    /// <value>Bitcoin address type (only for bitcoin chain)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BitcoinAddressTypeEnum
    {
        /// <summary>
        /// Enum P2pkh for value: p2pkh
        /// </summary>
        [EnumMember(Value = "p2pkh")]
        P2pkh = 1,

        /// <summary>
        /// Enum P2sh for value: p2sh
        /// </summary>
        [EnumMember(Value = "p2sh")]
        P2sh = 2,

        /// <summary>
        /// Enum P2wpkh for value: p2wpkh
        /// </summary>
        [EnumMember(Value = "p2wpkh")]
        P2wpkh = 3,

        /// <summary>
        /// Enum P2wsh for value: p2wsh
        /// </summary>
        [EnumMember(Value = "p2wsh")]
        P2wsh = 4,

        /// <summary>
        /// Enum P2tr for value: p2tr
        /// </summary>
        [EnumMember(Value = "p2tr")]
        P2tr = 5
    }

}
