/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// CompleteImportPrivateKeyResponseDto
    /// </summary>
    [DataContract(Name = "CompleteImportPrivateKeyResponseDto")]
    internal partial class CompleteImportPrivateKeyResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteImportPrivateKeyResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompleteImportPrivateKeyResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteImportPrivateKeyResponseDto" /> class.
        /// </summary>
        /// <param name="account">Imported account (required).</param>
        /// <param name="accountAddress">Account address for the imported chain (required).</param>
        /// <param name="accountSource">Account source information (required).</param>
        public CompleteImportPrivateKeyResponseDto(AccountResponseDto account = default(AccountResponseDto), AccountAddressResponseDto accountAddress = default(AccountAddressResponseDto), AccountSourceResponseDto accountSource = default(AccountSourceResponseDto))
        {
            // to ensure "account" is required (not null)
            if (account == null)
            {
                throw new ArgumentNullException("account is a required property for CompleteImportPrivateKeyResponseDto and cannot be null");
            }
            this.Account = account;
            // to ensure "accountAddress" is required (not null)
            if (accountAddress == null)
            {
                throw new ArgumentNullException("accountAddress is a required property for CompleteImportPrivateKeyResponseDto and cannot be null");
            }
            this.AccountAddress = accountAddress;
            // to ensure "accountSource" is required (not null)
            if (accountSource == null)
            {
                throw new ArgumentNullException("accountSource is a required property for CompleteImportPrivateKeyResponseDto and cannot be null");
            }
            this.AccountSource = accountSource;
        }

        /// <summary>
        /// Imported account
        /// </summary>
        /// <value>Imported account</value>
        [DataMember(Name = "account", IsRequired = true, EmitDefaultValue = true)]
        public AccountResponseDto Account { get; set; }

        /// <summary>
        /// Account address for the imported chain
        /// </summary>
        /// <value>Account address for the imported chain</value>
        [DataMember(Name = "accountAddress", IsRequired = true, EmitDefaultValue = true)]
        public AccountAddressResponseDto AccountAddress { get; set; }

        /// <summary>
        /// Account source information
        /// </summary>
        /// <value>Account source information</value>
        [DataMember(Name = "accountSource", IsRequired = true, EmitDefaultValue = true)]
        public AccountSourceResponseDto AccountSource { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompleteImportPrivateKeyResponseDto {\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  AccountAddress: ").Append(AccountAddress).Append("\n");
            sb.Append("  AccountSource: ").Append(AccountSource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
