/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// CompleteOtpLoginResponseDto
    /// </summary>
    [DataContract(Name = "CompleteOtpLoginResponseDto")]
    internal partial class CompleteOtpLoginResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteOtpLoginResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompleteOtpLoginResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteOtpLoginResponseDto" /> class.
        /// </summary>
        /// <param name="user">Peak User (required).</param>
        /// <param name="sessionJwt">Turnkey session JWT for authentication (required).</param>
        /// <param name="isNewUser">Whether this is a newly created user (required).</param>
        /// <param name="accountSource">Created account source (only present for new users).</param>
        /// <param name="account">Created default account (only present for new users).</param>
        /// <param name="accountAddresses">Created account addresses (EVM, Bitcoin, Solana, Sui) (only present for new users).</param>
        public CompleteOtpLoginResponseDto(UserResponseDto user = default(UserResponseDto), string sessionJwt = default(string), bool isNewUser = default(bool), AccountSourceResponseDto accountSource = default(AccountSourceResponseDto), AccountResponseDto account = default(AccountResponseDto), List<AccountAddressResponseDto> accountAddresses = default(List<AccountAddressResponseDto>))
        {
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for CompleteOtpLoginResponseDto and cannot be null");
            }
            this.User = user;
            // to ensure "sessionJwt" is required (not null)
            if (sessionJwt == null)
            {
                throw new ArgumentNullException("sessionJwt is a required property for CompleteOtpLoginResponseDto and cannot be null");
            }
            this.SessionJwt = sessionJwt;
            this.IsNewUser = isNewUser;
            this.AccountSource = accountSource;
            this.Account = account;
            this.AccountAddresses = accountAddresses;
        }

        /// <summary>
        /// Peak User
        /// </summary>
        /// <value>Peak User</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public UserResponseDto User { get; set; }

        /// <summary>
        /// Turnkey session JWT for authentication
        /// </summary>
        /// <value>Turnkey session JWT for authentication</value>
        [DataMember(Name = "sessionJwt", IsRequired = true, EmitDefaultValue = true)]
        public string SessionJwt { get; set; }

        /// <summary>
        /// Whether this is a newly created user
        /// </summary>
        /// <value>Whether this is a newly created user</value>
        [DataMember(Name = "isNewUser", IsRequired = true, EmitDefaultValue = true)]
        public bool IsNewUser { get; set; }

        /// <summary>
        /// Created account source (only present for new users)
        /// </summary>
        /// <value>Created account source (only present for new users)</value>
        [DataMember(Name = "accountSource", EmitDefaultValue = false)]
        public AccountSourceResponseDto AccountSource { get; set; }

        /// <summary>
        /// Created default account (only present for new users)
        /// </summary>
        /// <value>Created default account (only present for new users)</value>
        [DataMember(Name = "account", EmitDefaultValue = false)]
        public AccountResponseDto Account { get; set; }

        /// <summary>
        /// Created account addresses (EVM, Bitcoin, Solana, Sui) (only present for new users)
        /// </summary>
        /// <value>Created account addresses (EVM, Bitcoin, Solana, Sui) (only present for new users)</value>
        [DataMember(Name = "accountAddresses", EmitDefaultValue = false)]
        public List<AccountAddressResponseDto> AccountAddresses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompleteOtpLoginResponseDto {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  SessionJwt: ").Append(SessionJwt).Append("\n");
            sb.Append("  IsNewUser: ").Append(IsNewUser).Append("\n");
            sb.Append("  AccountSource: ").Append(AccountSource).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  AccountAddresses: ").Append(AccountAddresses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
