/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// CompleteOtpLoginRequestDto
    /// </summary>
    [DataContract(Name = "CompleteOtpLoginRequestDto")]
    internal partial class CompleteOtpLoginRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteOtpLoginRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompleteOtpLoginRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteOtpLoginRequestDto" /> class.
        /// </summary>
        /// <param name="email">User email address (required).</param>
        /// <param name="otpId">OTP ID returned from init-otp-login (required).</param>
        /// <param name="otpCode">OTP code sent to user email (required).</param>
        /// <param name="targetPublicKey">Target public key for session creation (required).</param>
        /// <param name="signup">Whether to create a new user if not exists. Defaults to true (unified flow). (default to true).</param>
        public CompleteOtpLoginRequestDto(string email = default(string), string otpId = default(string), string otpCode = default(string), string targetPublicKey = default(string), bool signup = true)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for CompleteOtpLoginRequestDto and cannot be null");
            }
            this.Email = email;
            // to ensure "otpId" is required (not null)
            if (otpId == null)
            {
                throw new ArgumentNullException("otpId is a required property for CompleteOtpLoginRequestDto and cannot be null");
            }
            this.OtpId = otpId;
            // to ensure "otpCode" is required (not null)
            if (otpCode == null)
            {
                throw new ArgumentNullException("otpCode is a required property for CompleteOtpLoginRequestDto and cannot be null");
            }
            this.OtpCode = otpCode;
            // to ensure "targetPublicKey" is required (not null)
            if (targetPublicKey == null)
            {
                throw new ArgumentNullException("targetPublicKey is a required property for CompleteOtpLoginRequestDto and cannot be null");
            }
            this.TargetPublicKey = targetPublicKey;
            this.Signup = signup;
        }

        /// <summary>
        /// User email address
        /// </summary>
        /// <value>User email address</value>
        /*
        <example>test@test.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// OTP ID returned from init-otp-login
        /// </summary>
        /// <value>OTP ID returned from init-otp-login</value>
        /*
        <example>00000000-0000-0000-0000-000000000000</example>
        */
        [DataMember(Name = "otpId", IsRequired = true, EmitDefaultValue = true)]
        public string OtpId { get; set; }

        /// <summary>
        /// OTP code sent to user email
        /// </summary>
        /// <value>OTP code sent to user email</value>
        /*
        <example>123456</example>
        */
        [DataMember(Name = "otpCode", IsRequired = true, EmitDefaultValue = true)]
        public string OtpCode { get; set; }

        /// <summary>
        /// Target public key for session creation
        /// </summary>
        /// <value>Target public key for session creation</value>
        /*
        <example>MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...</example>
        */
        [DataMember(Name = "targetPublicKey", IsRequired = true, EmitDefaultValue = true)]
        public string TargetPublicKey { get; set; }

        /// <summary>
        /// Whether to create a new user if not exists. Defaults to true (unified flow).
        /// </summary>
        /// <value>Whether to create a new user if not exists. Defaults to true (unified flow).</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "signup", EmitDefaultValue = true)]
        public bool Signup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompleteOtpLoginRequestDto {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  OtpId: ").Append(OtpId).Append("\n");
            sb.Append("  OtpCode: ").Append(OtpCode).Append("\n");
            sb.Append("  TargetPublicKey: ").Append(TargetPublicKey).Append("\n");
            sb.Append("  Signup: ").Append(Signup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
