/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// CompleteOtpLoginResponseDto
    /// </summary>
    [DataContract(Name = "CompleteOtpLoginResponseDto")]
    public partial class CompleteOtpLoginResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteOtpLoginResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompleteOtpLoginResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompleteOtpLoginResponseDto" /> class.
        /// </summary>
        /// <param name="user">Peak User (required).</param>
        /// <param name="sessionJwt">Turnkey session JWT for authentication (required).</param>
        public CompleteOtpLoginResponseDto(UserResponseDto user = default(UserResponseDto), string sessionJwt = default(string))
        {
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for CompleteOtpLoginResponseDto and cannot be null");
            }
            this.User = user;
            // to ensure "sessionJwt" is required (not null)
            if (sessionJwt == null)
            {
                throw new ArgumentNullException("sessionJwt is a required property for CompleteOtpLoginResponseDto and cannot be null");
            }
            this.SessionJwt = sessionJwt;
        }

        /// <summary>
        /// Peak User
        /// </summary>
        /// <value>Peak User</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public UserResponseDto User { get; set; }

        /// <summary>
        /// Turnkey session JWT for authentication
        /// </summary>
        /// <value>Turnkey session JWT for authentication</value>
        [DataMember(Name = "sessionJwt", IsRequired = true, EmitDefaultValue = true)]
        public string SessionJwt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompleteOtpLoginResponseDto {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  SessionJwt: ").Append(SessionJwt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
