/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// CreateAccountRequestDto
    /// </summary>
    [DataContract(Name = "CreateAccountRequestDto")]
    public partial class CreateAccountRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAccountRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAccountRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAccountRequestDto" /> class.
        /// </summary>
        /// <param name="signedCreateWalletAccountsRequest">Signed create wallet accounts request. The walletId in body.parameters is used to identify the account source. (required).</param>
        /// <param name="displayName">User-defined display name.</param>
        public CreateAccountRequestDto(SignedRequest signedCreateWalletAccountsRequest = default(SignedRequest), string displayName = default(string))
        {
            // to ensure "signedCreateWalletAccountsRequest" is required (not null)
            if (signedCreateWalletAccountsRequest == null)
            {
                throw new ArgumentNullException("signedCreateWalletAccountsRequest is a required property for CreateAccountRequestDto and cannot be null");
            }
            this.SignedCreateWalletAccountsRequest = signedCreateWalletAccountsRequest;
            this.DisplayName = displayName;
        }

        /// <summary>
        /// Signed create wallet accounts request. The walletId in body.parameters is used to identify the account source.
        /// </summary>
        /// <value>Signed create wallet accounts request. The walletId in body.parameters is used to identify the account source.</value>
        [DataMember(Name = "signedCreateWalletAccountsRequest", IsRequired = true, EmitDefaultValue = true)]
        public SignedRequest SignedCreateWalletAccountsRequest { get; set; }

        /// <summary>
        /// User-defined display name
        /// </summary>
        /// <value>User-defined display name</value>
        /*
        <example>My Account</example>
        */
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAccountRequestDto {\n");
            sb.Append("  SignedCreateWalletAccountsRequest: ").Append(SignedCreateWalletAccountsRequest).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
