/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// DeleteUserRequestDto
    /// </summary>
    [DataContract(Name = "DeleteUserRequestDto")]
    public partial class DeleteUserRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteUserRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeleteUserRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteUserRequestDto" /> class.
        /// </summary>
        /// <param name="signedDeleteSubOrganizationRequest">Signed delete sub organization request (required).</param>
        public DeleteUserRequestDto(SignedRequest signedDeleteSubOrganizationRequest = default(SignedRequest))
        {
            // to ensure "signedDeleteSubOrganizationRequest" is required (not null)
            if (signedDeleteSubOrganizationRequest == null)
            {
                throw new ArgumentNullException("signedDeleteSubOrganizationRequest is a required property for DeleteUserRequestDto and cannot be null");
            }
            this.SignedDeleteSubOrganizationRequest = signedDeleteSubOrganizationRequest;
        }

        /// <summary>
        /// Signed delete sub organization request
        /// </summary>
        /// <value>Signed delete sub organization request</value>
        [DataMember(Name = "signedDeleteSubOrganizationRequest", IsRequired = true, EmitDefaultValue = true)]
        public SignedRequest SignedDeleteSubOrganizationRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteUserRequestDto {\n");
            sb.Append("  SignedDeleteSubOrganizationRequest: ").Append(SignedDeleteSubOrganizationRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
