/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// DeleteUserResponseDto
    /// </summary>
    [DataContract(Name = "DeleteUserResponseDto")]
    public partial class DeleteUserResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteUserResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeleteUserResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteUserResponseDto" /> class.
        /// </summary>
        /// <param name="user">Deleted Peak user (required).</param>
        public DeleteUserResponseDto(UserResponseDto user = default(UserResponseDto))
        {
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for DeleteUserResponseDto and cannot be null");
            }
            this.User = user;
        }

        /// <summary>
        /// Deleted Peak user
        /// </summary>
        /// <value>Deleted Peak user</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public UserResponseDto User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteUserResponseDto {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
