/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// ErrorResponseDto
    /// </summary>
    [DataContract(Name = "ErrorResponseDto")]
    internal partial class ErrorResponseDto : IValidatableObject
    {
        /// <summary>
        /// HTTP status code
        /// </summary>
        /// <value>HTTP status code</value>
        [JsonConverter(typeof(StringEnumConverter))]
        internal enum StatusCodeEnum
        {
            /// <summary>
            /// Enum _400 for value: 400
            /// </summary>
            [EnumMember(Value = "400")]
            _400 = 1,

            /// <summary>
            /// Enum _401 for value: 401
            /// </summary>
            [EnumMember(Value = "401")]
            _401 = 2,

            /// <summary>
            /// Enum _403 for value: 403
            /// </summary>
            [EnumMember(Value = "403")]
            _403 = 3,

            /// <summary>
            /// Enum _404 for value: 404
            /// </summary>
            [EnumMember(Value = "404")]
            _404 = 4,

            /// <summary>
            /// Enum _409 for value: 409
            /// </summary>
            [EnumMember(Value = "409")]
            _409 = 5,

            /// <summary>
            /// Enum _429 for value: 429
            /// </summary>
            [EnumMember(Value = "429")]
            _429 = 6,

            /// <summary>
            /// Enum _500 for value: 500
            /// </summary>
            [EnumMember(Value = "500")]
            _500 = 7,

            /// <summary>
            /// Enum _502 for value: 502
            /// </summary>
            [EnumMember(Value = "502")]
            _502 = 8,

            /// <summary>
            /// Enum _503 for value: 503
            /// </summary>
            [EnumMember(Value = "503")]
            _503 = 9
        }


        /// <summary>
        /// HTTP status code
        /// </summary>
        /// <value>HTTP status code</value>
        /*
        <example>400</example>
        */
        [DataMember(Name = "statusCode", IsRequired = true, EmitDefaultValue = true)]
        public StatusCodeEnum StatusCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrorResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorResponseDto" /> class.
        /// </summary>
        /// <param name="statusCode">HTTP status code (required).</param>
        /// <param name="errorCode">Machine-readable error code for client-side handling. This is a stable contract. (required).</param>
        /// <param name="message">Human-readable error message for debugging. Do not use for programmatic handling. (required).</param>
        /// <param name="details">Additional error details (e.g., validation errors).</param>
        /// <param name="timestamp">ISO 8601 timestamp when the error occurred (required).</param>
        /// <param name="path">Request path that caused the error (required).</param>
        public ErrorResponseDto(StatusCodeEnum statusCode = default(StatusCodeEnum), string errorCode = default(string), string message = default(string), Object details = default(Object), string timestamp = default(string), string path = default(string))
        {
            this.StatusCode = statusCode;
            // to ensure "errorCode" is required (not null)
            if (errorCode == null)
            {
                throw new ArgumentNullException("errorCode is a required property for ErrorResponseDto and cannot be null");
            }
            this.ErrorCode = errorCode;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for ErrorResponseDto and cannot be null");
            }
            this.Message = message;
            // to ensure "timestamp" is required (not null)
            if (timestamp == null)
            {
                throw new ArgumentNullException("timestamp is a required property for ErrorResponseDto and cannot be null");
            }
            this.Timestamp = timestamp;
            // to ensure "path" is required (not null)
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for ErrorResponseDto and cannot be null");
            }
            this.Path = path;
            this.Details = details;
        }

        /// <summary>
        /// Machine-readable error code for client-side handling. This is a stable contract.
        /// </summary>
        /// <value>Machine-readable error code for client-side handling. This is a stable contract.</value>
        /*
        <example>REQUEST_VALIDATION_ERROR</example>
        */
        [DataMember(Name = "errorCode", IsRequired = true, EmitDefaultValue = true)]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Human-readable error message for debugging. Do not use for programmatic handling.
        /// </summary>
        /// <value>Human-readable error message for debugging. Do not use for programmatic handling.</value>
        /*
        <example>Invalid request data</example>
        */
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Additional error details (e.g., validation errors)
        /// </summary>
        /// <value>Additional error details (e.g., validation errors)</value>
        /*
        <example>{&quot;field&quot;:&quot;email&quot;,&quot;reason&quot;:&quot;must be a valid email&quot;}</example>
        */
        [DataMember(Name = "details", EmitDefaultValue = false)]
        public Object Details { get; set; }

        /// <summary>
        /// ISO 8601 timestamp when the error occurred
        /// </summary>
        /// <value>ISO 8601 timestamp when the error occurred</value>
        /*
        <example>2024-01-01T00:00:00.000Z</example>
        */
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = true)]
        public string Timestamp { get; set; }

        /// <summary>
        /// Request path that caused the error
        /// </summary>
        /// <value>Request path that caused the error</value>
        /*
        <example>/public-api/v1/auth/login</example>
        */
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        public string Path { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorResponseDto {\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
