/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// EvmSignMessageRequestDto
    /// </summary>
    [DataContract(Name = "EvmSignMessageRequestDto")]
    public partial class EvmSignMessageRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EvmSignMessageRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EvmSignMessageRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EvmSignMessageRequestDto" /> class.
        /// </summary>
        /// <param name="signedSignRawPayloadRequest">Signed Turnkey request for signing raw payloads (required).</param>
        public EvmSignMessageRequestDto(SignedRequest signedSignRawPayloadRequest = default(SignedRequest))
        {
            // to ensure "signedSignRawPayloadRequest" is required (not null)
            if (signedSignRawPayloadRequest == null)
            {
                throw new ArgumentNullException("signedSignRawPayloadRequest is a required property for EvmSignMessageRequestDto and cannot be null");
            }
            this.SignedSignRawPayloadRequest = signedSignRawPayloadRequest;
        }

        /// <summary>
        /// Signed Turnkey request for signing raw payloads
        /// </summary>
        /// <value>Signed Turnkey request for signing raw payloads</value>
        [DataMember(Name = "signedSignRawPayloadRequest", IsRequired = true, EmitDefaultValue = true)]
        public SignedRequest SignedSignRawPayloadRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EvmSignMessageRequestDto {\n");
            sb.Append("  SignedSignRawPayloadRequest: ").Append(SignedSignRawPayloadRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
