/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// ExportPrivateKeyResponseDto
    /// </summary>
    [DataContract(Name = "ExportPrivateKeyResponseDto")]
    public partial class ExportPrivateKeyResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportPrivateKeyResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExportPrivateKeyResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportPrivateKeyResponseDto" /> class.
        /// </summary>
        /// <param name="exportBundle">Encrypted private key export bundle (required).</param>
        public ExportPrivateKeyResponseDto(string exportBundle = default(string))
        {
            // to ensure "exportBundle" is required (not null)
            if (exportBundle == null)
            {
                throw new ArgumentNullException("exportBundle is a required property for ExportPrivateKeyResponseDto and cannot be null");
            }
            this.ExportBundle = exportBundle;
        }

        /// <summary>
        /// Encrypted private key export bundle
        /// </summary>
        /// <value>Encrypted private key export bundle</value>
        [DataMember(Name = "exportBundle", IsRequired = true, EmitDefaultValue = true)]
        public string ExportBundle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExportPrivateKeyResponseDto {\n");
            sb.Append("  ExportBundle: ").Append(ExportBundle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
