/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// ExportRecoveryPhraseRequestDto
    /// </summary>
    [DataContract(Name = "ExportRecoveryPhraseRequestDto")]
    public partial class ExportRecoveryPhraseRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportRecoveryPhraseRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExportRecoveryPhraseRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportRecoveryPhraseRequestDto" /> class.
        /// </summary>
        /// <param name="signedExportWalletRequest">Signed export wallet request. The walletId in body.parameters is used to identify the recovery phrase. (required).</param>
        public ExportRecoveryPhraseRequestDto(SignedRequest signedExportWalletRequest = default(SignedRequest))
        {
            // to ensure "signedExportWalletRequest" is required (not null)
            if (signedExportWalletRequest == null)
            {
                throw new ArgumentNullException("signedExportWalletRequest is a required property for ExportRecoveryPhraseRequestDto and cannot be null");
            }
            this.SignedExportWalletRequest = signedExportWalletRequest;
        }

        /// <summary>
        /// Signed export wallet request. The walletId in body.parameters is used to identify the recovery phrase.
        /// </summary>
        /// <value>Signed export wallet request. The walletId in body.parameters is used to identify the recovery phrase.</value>
        [DataMember(Name = "signedExportWalletRequest", IsRequired = true, EmitDefaultValue = true)]
        public SignedRequest SignedExportWalletRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExportRecoveryPhraseRequestDto {\n");
            sb.Append("  SignedExportWalletRequest: ").Append(SignedExportWalletRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
