/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// GetAccountSourceByAccountIdResponseDto
    /// </summary>
    [DataContract(Name = "GetAccountSourceByAccountIdResponseDto")]
    public partial class GetAccountSourceByAccountIdResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccountSourceByAccountIdResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetAccountSourceByAccountIdResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccountSourceByAccountIdResponseDto" /> class.
        /// </summary>
        /// <param name="accountSource">Account source (required).</param>
        public GetAccountSourceByAccountIdResponseDto(AccountSourceResponseDto accountSource = default(AccountSourceResponseDto))
        {
            // to ensure "accountSource" is required (not null)
            if (accountSource == null)
            {
                throw new ArgumentNullException("accountSource is a required property for GetAccountSourceByAccountIdResponseDto and cannot be null");
            }
            this.AccountSource = accountSource;
        }

        /// <summary>
        /// Account source
        /// </summary>
        /// <value>Account source</value>
        [DataMember(Name = "accountSource", IsRequired = true, EmitDefaultValue = true)]
        public AccountSourceResponseDto AccountSource { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAccountSourceByAccountIdResponseDto {\n");
            sb.Append("  AccountSource: ").Append(AccountSource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
