/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// GoogleConfigResponseDto
    /// </summary>
    [DataContract(Name = "GoogleConfigResponseDto")]
    public partial class GoogleConfigResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleConfigResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GoogleConfigResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleConfigResponseDto" /> class.
        /// </summary>
        /// <param name="clientId">Google OAuth Client ID (required).</param>
        /// <param name="callbackUrl">Google OAuth Callback URL (required).</param>
        public GoogleConfigResponseDto(string clientId = default(string), string callbackUrl = default(string))
        {
            // to ensure "clientId" is required (not null)
            if (clientId == null)
            {
                throw new ArgumentNullException("clientId is a required property for GoogleConfigResponseDto and cannot be null");
            }
            this.ClientId = clientId;
            // to ensure "callbackUrl" is required (not null)
            if (callbackUrl == null)
            {
                throw new ArgumentNullException("callbackUrl is a required property for GoogleConfigResponseDto and cannot be null");
            }
            this.CallbackUrl = callbackUrl;
        }

        /// <summary>
        /// Google OAuth Client ID
        /// </summary>
        /// <value>Google OAuth Client ID</value>
        /*
        <example>123456789-abc.apps.googleusercontent.com</example>
        */
        [DataMember(Name = "clientId", IsRequired = true, EmitDefaultValue = true)]
        public string ClientId { get; set; }

        /// <summary>
        /// Google OAuth Callback URL
        /// </summary>
        /// <value>Google OAuth Callback URL</value>
        /*
        <example>https://wallet.peak-dev.xyz/auth/google/callback</example>
        */
        [DataMember(Name = "callbackUrl", IsRequired = true, EmitDefaultValue = true)]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoogleConfigResponseDto {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
