/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// InitOtpLoginRequestDto
    /// </summary>
    [DataContract(Name = "InitOtpLoginRequestDto")]
    public partial class InitOtpLoginRequestDto : IValidatableObject
    {
        /// <summary>
        /// Language for the OTP email template
        /// </summary>
        /// <value>Language for the OTP email template</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LanguageEnum
        {
            /// <summary>
            /// Enum En for value: en
            /// </summary>
            [EnumMember(Value = "en")]
            En = 1,

            /// <summary>
            /// Enum Ja for value: ja
            /// </summary>
            [EnumMember(Value = "ja")]
            Ja = 2
        }


        /// <summary>
        /// Language for the OTP email template
        /// </summary>
        /// <value>Language for the OTP email template</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public LanguageEnum? Language { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitOtpLoginRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InitOtpLoginRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitOtpLoginRequestDto" /> class.
        /// </summary>
        /// <param name="email">Email of the user (required).</param>
        /// <param name="language">Language for the OTP email template (default to LanguageEnum.En).</param>
        public InitOtpLoginRequestDto(string email = default(string), LanguageEnum? language = LanguageEnum.En)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for InitOtpLoginRequestDto and cannot be null");
            }
            this.Email = email;
            this.Language = language;
        }

        /// <summary>
        /// Email of the user
        /// </summary>
        /// <value>Email of the user</value>
        /*
        <example>test@test.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitOtpLoginRequestDto {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
