/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// InitImportRecoveryPhraseRequestDto
    /// </summary>
    [DataContract(Name = "InitImportRecoveryPhraseRequestDto")]
    public partial class InitImportRecoveryPhraseRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitImportRecoveryPhraseRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InitImportRecoveryPhraseRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitImportRecoveryPhraseRequestDto" /> class.
        /// </summary>
        /// <param name="signedInitImportWalletRequest">Signed init import wallet request (required).</param>
        public InitImportRecoveryPhraseRequestDto(SignedRequest signedInitImportWalletRequest = default(SignedRequest))
        {
            // to ensure "signedInitImportWalletRequest" is required (not null)
            if (signedInitImportWalletRequest == null)
            {
                throw new ArgumentNullException("signedInitImportWalletRequest is a required property for InitImportRecoveryPhraseRequestDto and cannot be null");
            }
            this.SignedInitImportWalletRequest = signedInitImportWalletRequest;
        }

        /// <summary>
        /// Signed init import wallet request
        /// </summary>
        /// <value>Signed init import wallet request</value>
        [DataMember(Name = "signedInitImportWalletRequest", IsRequired = true, EmitDefaultValue = true)]
        public SignedRequest SignedInitImportWalletRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitImportRecoveryPhraseRequestDto {\n");
            sb.Append("  SignedInitImportWalletRequest: ").Append(SignedInitImportWalletRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
