/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// InitImportRecoveryPhraseResponseDto
    /// </summary>
    [DataContract(Name = "InitImportRecoveryPhraseResponseDto")]
    internal partial class InitImportRecoveryPhraseResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitImportRecoveryPhraseResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InitImportRecoveryPhraseResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitImportRecoveryPhraseResponseDto" /> class.
        /// </summary>
        /// <param name="importBundle">Import bundle containing a public key and signature to use for importing client data. (required).</param>
        public InitImportRecoveryPhraseResponseDto(string importBundle = default(string))
        {
            // to ensure "importBundle" is required (not null)
            if (importBundle == null)
            {
                throw new ArgumentNullException("importBundle is a required property for InitImportRecoveryPhraseResponseDto and cannot be null");
            }
            this.ImportBundle = importBundle;
        }

        /// <summary>
        /// Import bundle containing a public key and signature to use for importing client data.
        /// </summary>
        /// <value>Import bundle containing a public key and signature to use for importing client data.</value>
        [DataMember(Name = "importBundle", IsRequired = true, EmitDefaultValue = true)]
        public string ImportBundle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitImportRecoveryPhraseResponseDto {\n");
            sb.Append("  ImportBundle: ").Append(ImportBundle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
