/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// ListAccountAddressesResponseDto
    /// </summary>
    [DataContract(Name = "ListAccountAddressesResponseDto")]
    public partial class ListAccountAddressesResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListAccountAddressesResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListAccountAddressesResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListAccountAddressesResponseDto" /> class.
        /// </summary>
        /// <param name="accountAddresses">List of account addresses (required).</param>
        public ListAccountAddressesResponseDto(List<AccountAddressResponseDto> accountAddresses = default(List<AccountAddressResponseDto>))
        {
            // to ensure "accountAddresses" is required (not null)
            if (accountAddresses == null)
            {
                throw new ArgumentNullException("accountAddresses is a required property for ListAccountAddressesResponseDto and cannot be null");
            }
            this.AccountAddresses = accountAddresses;
        }

        /// <summary>
        /// List of account addresses
        /// </summary>
        /// <value>List of account addresses</value>
        [DataMember(Name = "accountAddresses", IsRequired = true, EmitDefaultValue = true)]
        public List<AccountAddressResponseDto> AccountAddresses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListAccountAddressesResponseDto {\n");
            sb.Append("  AccountAddresses: ").Append(AccountAddresses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
