/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// ListAccountsResponseDto
    /// </summary>
    [DataContract(Name = "ListAccountsResponseDto")]
    public partial class ListAccountsResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListAccountsResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListAccountsResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListAccountsResponseDto" /> class.
        /// </summary>
        /// <param name="accounts">List of accounts (required).</param>
        public ListAccountsResponseDto(List<AccountResponseDto> accounts = default(List<AccountResponseDto>))
        {
            // to ensure "accounts" is required (not null)
            if (accounts == null)
            {
                throw new ArgumentNullException("accounts is a required property for ListAccountsResponseDto and cannot be null");
            }
            this.Accounts = accounts;
        }

        /// <summary>
        /// List of accounts
        /// </summary>
        /// <value>List of accounts</value>
        [DataMember(Name = "accounts", IsRequired = true, EmitDefaultValue = true)]
        public List<AccountResponseDto> Accounts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListAccountsResponseDto {\n");
            sb.Append("  Accounts: ").Append(Accounts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
