/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// Chain type for the imported private key
    /// </summary>
    /// <value>Chain type for the imported private key</value>
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum PrivateKeyImportExportSupportedChainTypeEnum
    {
        /// <summary>
        /// Enum Evm for value: evm
        /// </summary>
        [EnumMember(Value = "evm")]
        Evm = 1,

        /// <summary>
        /// Enum Bitcoin for value: bitcoin
        /// </summary>
        [EnumMember(Value = "bitcoin")]
        Bitcoin = 2,

        /// <summary>
        /// Enum Solana for value: solana
        /// </summary>
        [EnumMember(Value = "solana")]
        Solana = 3,

        /// <summary>
        /// Enum Sui for value: sui
        /// </summary>
        [EnumMember(Value = "sui")]
        Sui = 4
    }

}
