/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// SignedRequest
    /// </summary>
    [DataContract(Name = "SignedRequest")]
    internal partial class SignedRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignedRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignedRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignedRequest" /> class.
        /// </summary>
        /// <param name="body">Body (required).</param>
        /// <param name="stamp">Stamp (required).</param>
        /// <param name="url">URL (required).</param>
        public SignedRequest(string body = default(string), Stamp stamp = default(Stamp), string url = default(string))
        {
            // to ensure "body" is required (not null)
            if (body == null)
            {
                throw new ArgumentNullException("body is a required property for SignedRequest and cannot be null");
            }
            this.Body = body;
            // to ensure "stamp" is required (not null)
            if (stamp == null)
            {
                throw new ArgumentNullException("stamp is a required property for SignedRequest and cannot be null");
            }
            this.Stamp = stamp;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for SignedRequest and cannot be null");
            }
            this.Url = url;
        }

        /// <summary>
        /// Body
        /// </summary>
        /// <value>Body</value>
        /*
        <example>{&quot;organizationId&quot;:&quot;c0731898-7908-472a-aaff-373417cdb213&quot;}</example>
        */
        [DataMember(Name = "body", IsRequired = true, EmitDefaultValue = true)]
        public string Body { get; set; }

        /// <summary>
        /// Stamp
        /// </summary>
        /// <value>Stamp</value>
        [DataMember(Name = "stamp", IsRequired = true, EmitDefaultValue = true)]
        public Stamp Stamp { get; set; }

        /// <summary>
        /// URL
        /// </summary>
        /// <value>URL</value>
        /*
        <example>https://api.turnkey.com/public/v1/query/whoami</example>
        */
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignedRequest {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Stamp: ").Append(Stamp).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
