/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// SignupResponseDto
    /// </summary>
    [DataContract(Name = "SignupResponseDto")]
    public partial class SignupResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignupResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignupResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignupResponseDto" /> class.
        /// </summary>
        /// <param name="user">Created Peak User (required).</param>
        /// <param name="accountSource">Created account source (required).</param>
        /// <param name="account">Created default account (required).</param>
        /// <param name="accountAddresses">Created account addresses (EVM, Bitcoin, Solana) (required).</param>
        public SignupResponseDto(UserResponseDto user = default(UserResponseDto), AccountSourceResponseDto accountSource = default(AccountSourceResponseDto), AccountResponseDto account = default(AccountResponseDto), List<AccountAddressResponseDto> accountAddresses = default(List<AccountAddressResponseDto>))
        {
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for SignupResponseDto and cannot be null");
            }
            this.User = user;
            // to ensure "accountSource" is required (not null)
            if (accountSource == null)
            {
                throw new ArgumentNullException("accountSource is a required property for SignupResponseDto and cannot be null");
            }
            this.AccountSource = accountSource;
            // to ensure "account" is required (not null)
            if (account == null)
            {
                throw new ArgumentNullException("account is a required property for SignupResponseDto and cannot be null");
            }
            this.Account = account;
            // to ensure "accountAddresses" is required (not null)
            if (accountAddresses == null)
            {
                throw new ArgumentNullException("accountAddresses is a required property for SignupResponseDto and cannot be null");
            }
            this.AccountAddresses = accountAddresses;
        }

        /// <summary>
        /// Created Peak User
        /// </summary>
        /// <value>Created Peak User</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public UserResponseDto User { get; set; }

        /// <summary>
        /// Created account source
        /// </summary>
        /// <value>Created account source</value>
        [DataMember(Name = "accountSource", IsRequired = true, EmitDefaultValue = true)]
        public AccountSourceResponseDto AccountSource { get; set; }

        /// <summary>
        /// Created default account
        /// </summary>
        /// <value>Created default account</value>
        [DataMember(Name = "account", IsRequired = true, EmitDefaultValue = true)]
        public AccountResponseDto Account { get; set; }

        /// <summary>
        /// Created account addresses (EVM, Bitcoin, Solana)
        /// </summary>
        /// <value>Created account addresses (EVM, Bitcoin, Solana)</value>
        [DataMember(Name = "accountAddresses", IsRequired = true, EmitDefaultValue = true)]
        public List<AccountAddressResponseDto> AccountAddresses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignupResponseDto {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  AccountSource: ").Append(AccountSource).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  AccountAddresses: ").Append(AccountAddresses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
