/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// SolanaSignTransactionRequestDto
    /// </summary>
    [DataContract(Name = "SolanaSignTransactionRequestDto")]
    internal partial class SolanaSignTransactionRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SolanaSignTransactionRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SolanaSignTransactionRequestDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SolanaSignTransactionRequestDto" /> class.
        /// </summary>
        /// <param name="signedSignTransactionRequest">Signed transaction request with Turnkey stamp (required for secure signing) (required).</param>
        public SolanaSignTransactionRequestDto(SignedRequest signedSignTransactionRequest = default(SignedRequest))
        {
            // to ensure "signedSignTransactionRequest" is required (not null)
            if (signedSignTransactionRequest == null)
            {
                throw new ArgumentNullException("signedSignTransactionRequest is a required property for SolanaSignTransactionRequestDto and cannot be null");
            }
            this.SignedSignTransactionRequest = signedSignTransactionRequest;
        }

        /// <summary>
        /// Signed transaction request with Turnkey stamp (required for secure signing)
        /// </summary>
        /// <value>Signed transaction request with Turnkey stamp (required for secure signing)</value>
        [DataMember(Name = "signedSignTransactionRequest", IsRequired = true, EmitDefaultValue = true)]
        public SignedRequest SignedSignTransactionRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SolanaSignTransactionRequestDto {\n");
            sb.Append("  SignedSignTransactionRequest: ").Append(SignedSignTransactionRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
