/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// Stamp
    /// </summary>
    [DataContract(Name = "Stamp")]
    internal partial class Stamp : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Stamp" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Stamp() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Stamp" /> class.
        /// </summary>
        /// <param name="stampHeaderName">Stamp header name (required).</param>
        /// <param name="stampHeaderValue">Stamp header value (required).</param>
        public Stamp(string stampHeaderName = default(string), string stampHeaderValue = default(string))
        {
            // to ensure "stampHeaderName" is required (not null)
            if (stampHeaderName == null)
            {
                throw new ArgumentNullException("stampHeaderName is a required property for Stamp and cannot be null");
            }
            this.StampHeaderName = stampHeaderName;
            // to ensure "stampHeaderValue" is required (not null)
            if (stampHeaderValue == null)
            {
                throw new ArgumentNullException("stampHeaderValue is a required property for Stamp and cannot be null");
            }
            this.StampHeaderValue = stampHeaderValue;
        }

        /// <summary>
        /// Stamp header name
        /// </summary>
        /// <value>Stamp header name</value>
        /*
        <example>X-Stamp</example>
        */
        [DataMember(Name = "stampHeaderName", IsRequired = true, EmitDefaultValue = true)]
        public string StampHeaderName { get; set; }

        /// <summary>
        /// Stamp header value
        /// </summary>
        /// <value>Stamp header value</value>
        /*
        <example>eyJwdWJsaWNLZXkiOiIwMjVmNzg0ZjZhYjc1MzU5NTQ5NTBkZjMzZmJkMTVkMTMwNDFhMzNjNGIyMmY2ZDk4ZTMzYzJhYzU3Nzc5MTdjY2UiLCJzY2hlbWUiOiJTSUdOQVRVUkVfU0NIRU1FX1RLX0FQSV9QMjU2Iiwic2lnbmF0dXJlIjoiMzA0NDAyMjA0OWFmMjE3NzRiYWYwODI2NTZjYzgyYjZmODQ5ZTNlMmI4MDg2ZmYyMDNkMTQ4YWY3MTdiNGZhMDgxMjg3NDEyMDIyMDY4ZjQwYmU2Yjk4YTNjNWRjN2VlMmZlNjFhYmRiYzE3YzMwZjU0MjFlNzQxODBkMDZiNTcwM2Y0OTUyN2U5NjQifQ</example>
        */
        [DataMember(Name = "stampHeaderValue", IsRequired = true, EmitDefaultValue = true)]
        public string StampHeaderValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Stamp {\n");
            sb.Append("  StampHeaderName: ").Append(StampHeaderName).Append("\n");
            sb.Append("  StampHeaderValue: ").Append(StampHeaderValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
