/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// SuiSignTransactionResponseDto
    /// </summary>
    [DataContract(Name = "SuiSignTransactionResponseDto")]
    public partial class SuiSignTransactionResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuiSignTransactionResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SuiSignTransactionResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SuiSignTransactionResponseDto" /> class.
        /// </summary>
        /// <param name="signature">The Sui transaction signature (base64-encoded) (required).</param>
        public SuiSignTransactionResponseDto(string signature = default(string))
        {
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new ArgumentNullException("signature is a required property for SuiSignTransactionResponseDto and cannot be null");
            }
            this.Signature = signature;
        }

        /// <summary>
        /// The Sui transaction signature (base64-encoded)
        /// </summary>
        /// <value>The Sui transaction signature (base64-encoded)</value>
        /*
        <example>AQRvZ2...</example>
        */
        [DataMember(Name = "signature", IsRequired = true, EmitDefaultValue = true)]
        public string Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuiSignTransactionResponseDto {\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
