/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KyuzanInc.Peak.PublicApiClient.Client.OpenAPIDateConverter;

namespace KyuzanInc.Peak.PublicApiClient.Model
{
    /// <summary>
    /// SuiSignMessageResponseDto
    /// </summary>
    [DataContract(Name = "SuiSignMessageResponseDto")]
    internal partial class SuiSignMessageResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuiSignMessageResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SuiSignMessageResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SuiSignMessageResponseDto" /> class.
        /// </summary>
        /// <param name="signature">Signature in base64 format (97 bytes: flag + signature + publicKey) (required).</param>
        /// <param name="publicKey">Public key in base64 format.</param>
        public SuiSignMessageResponseDto(string signature = default(string), string publicKey = default(string))
        {
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new ArgumentNullException("signature is a required property for SuiSignMessageResponseDto and cannot be null");
            }
            this.Signature = signature;
            this.PublicKey = publicKey;
        }

        /// <summary>
        /// Signature in base64 format (97 bytes: flag + signature + publicKey)
        /// </summary>
        /// <value>Signature in base64 format (97 bytes: flag + signature + publicKey)</value>
        /*
        <example>AEZzWC8vm5SpLX5tqK...</example>
        */
        [DataMember(Name = "signature", IsRequired = true, EmitDefaultValue = true)]
        public string Signature { get; set; }

        /// <summary>
        /// Public key in base64 format
        /// </summary>
        /// <value>Public key in base64 format</value>
        /*
        <example>HN7cABqLq46Es1jh1DTUy9o9F...</example>
        */
        [DataMember(Name = "publicKey", EmitDefaultValue = false)]
        public string PublicKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuiSignMessageResponseDto {\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("  PublicKey: ").Append(PublicKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
