#!/bin/bash

# Fix MDX compatibility issues in generated Markdown files
# Preserve Examples while normalizing syntax that breaks MDX parsing
#
# Usage: OUTPUT_DIR=<path> ./fix-mdx-compatibility.sh
#   OUTPUT_DIR: Environment variable specifying the API docs directory

set -e

echo "🔧 Fixing MDX compatibility issues..."

# Use OUTPUT_DIR environment variable, or fall back to default
API_DIR="${OUTPUT_DIR:-../../../apps/peak-public-docs/docs/sdks-and-tools/peak-sdk-unity/api}"

if [ ! -d "$API_DIR" ]; then
    echo "❌ API directory not found: $API_DIR"
    exit 1
fi

for file in "$API_DIR"/*.md; do
    if [ -f "$file" ]; then
        echo "Processing: $(basename "$file")"

        BASENAME="$(basename "$file" .md)"

        # Ensure Docusaurus front matter exists (idempotent)
        if ! head -n 1 "$file" | grep -q '^---'; then
            TEMP_FILE="$(mktemp)"
            {
                echo "---"
                echo "id: $BASENAME"
                echo "title: $BASENAME"
                echo "---"
                echo
            } > "$TEMP_FILE"
            cat "$file" >> "$TEMP_FILE"
            mv "$TEMP_FILE" "$file"
        fi

        # Clean up escaped braces left by DocFX (keeps source readable + compatible with MDX)
        sed -i '' 's/\\{/{/g' "$file"
        sed -i '' 's/\\}/}/g' "$file"
        sed -i '' 's/\&lbrace;/{/g' "$file"
        sed -i '' 's/\&rbrace;/}/g' "$file"

        # Convert DocFX HTML code blocks into fenced code blocks for MDX friendliness
        perl -0pi -e 's/<pre><code class="lang-csharp">/\n```csharp\n/g' "$file"
        perl -0pi -e 's{</code></pre>}{\n```\n}g' "$file"

        # Trim redundant blank lines introduced by conversions (idempotent)
        perl -0pi -e 's/\n{3,}/\n\n/g' "$file"

        # Remove inheritance metadata sections that add noise in MDX output
        perl -0pi -e 's/^#### Inheritance\n(?:.+?\n)(?=^###|^##)//smg' "$file"
        perl -0pi -e 's/^#### Inherited Members\n(?:.+?\n)(?=^###|^##)//smg' "$file"

        # Encode generic type angle brackets emitted as "<Type\>" to avoid MDX JSX parsing
        perl -0pi -e 's/<([^>\n]+)\\>/&lt;$1&gt;/g' "$file"

        # Ensure headings and fenced blocks remain separated by a blank line for MDX
        perl -0pi -e 's/(```\n)(#+ )/$1\n$2/g' "$file"
        perl -0pi -e 's/(^|[^`])\n(#+ .+\n```)/$1\n\n$2/gm' "$file"
    fi
done

# Add autogenerated front matter to namespace index as well (if missing)
if [ -f "$API_DIR/Peak.md" ] && ! head -n 1 "$API_DIR/Peak.md" | grep -q '^---'; then
    TEMP_FILE="$(mktemp)"
    {
        echo "---"
        echo "id: Peak"
        echo "title: Peak Namespace"
        echo "---"
        echo
    } > "$TEMP_FILE"
    cat "$API_DIR/Peak.md" >> "$TEMP_FILE"
    mv "$TEMP_FILE" "$API_DIR/Peak.md"
fi

echo "✅ MDX compatibility fixes applied"

# Count the number of files that were processed
PROCESSED_FILES=$(find "$API_DIR" -name "*.md" -type f | wc -l)
echo "📄 Processed $PROCESSED_FILES file(s) — normalized Markdown for MDX"
