/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using KyuzanInc.Peak.PublicApiClient.Client;
using KyuzanInc.Peak.PublicApiClient.Model;

namespace KyuzanInc.Peak.PublicApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IAccountApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CreateAccountResponseDto</returns>
        CreateAccountResponseDto CreateAccount(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CreateAccountResponseDto</returns>
        ApiResponse<CreateAccountResponseDto> CreateAccountWithHttpInfo(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountAddressWithAccountAndSourceResponseDto</returns>
        GetAccountAddressWithAccountAndSourceResponseDto GetAddressDetail(string address, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountAddressWithAccountAndSourceResponseDto</returns>
        ApiResponse<GetAccountAddressWithAccountAndSourceResponseDto> GetAddressDetailWithHttpInfo(string address, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetMaxAccountIndexResponseDto</returns>
        GetMaxAccountIndexResponseDto GetMaxIndex(string accountSourceId, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetMaxAccountIndexResponseDto</returns>
        ApiResponse<GetMaxAccountIndexResponseDto> GetMaxIndexWithHttpInfo(string accountSourceId, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountSourceResponseDto</returns>
        GetAccountSourceResponseDto GetSource(string accountSourceId, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountSourceResponseDto</returns>
        ApiResponse<GetAccountSourceResponseDto> GetSourceWithHttpInfo(string accountSourceId, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountSourceByAccountIdResponseDto</returns>
        GetAccountSourceByAccountIdResponseDto GetSourceByAccount(string accountId, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountSourceByAccountIdResponseDto</returns>
        ApiResponse<GetAccountSourceByAccountIdResponseDto> GetSourceByAccountWithHttpInfo(string accountId, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ListAccountsResponseDto</returns>
        ListAccountsResponseDto ListAccounts(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ListAccountsResponseDto</returns>
        ApiResponse<ListAccountsResponseDto> ListAccountsWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ListAccountAddressesResponseDto</returns>
        ListAccountAddressesResponseDto ListAddresses(string accountId, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ListAccountAddressesResponseDto</returns>
        ApiResponse<ListAccountAddressesResponseDto> ListAddressesWithHttpInfo(string accountId, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateAccountDisplayNameResponseDto</returns>
        UpdateAccountDisplayNameResponseDto UpdateDisplayName(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateAccountDisplayNameResponseDto</returns>
        ApiResponse<UpdateAccountDisplayNameResponseDto> UpdateDisplayNameWithHttpInfo(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IAccountApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateAccountResponseDto</returns>
        System.Threading.Tasks.Task<CreateAccountResponseDto> CreateAccountAsync(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateAccountResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateAccountResponseDto>> CreateAccountWithHttpInfoAsync(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountAddressWithAccountAndSourceResponseDto</returns>
        System.Threading.Tasks.Task<GetAccountAddressWithAccountAndSourceResponseDto> GetAddressDetailAsync(string address, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountAddressWithAccountAndSourceResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAccountAddressWithAccountAndSourceResponseDto>> GetAddressDetailWithHttpInfoAsync(string address, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetMaxAccountIndexResponseDto</returns>
        System.Threading.Tasks.Task<GetMaxAccountIndexResponseDto> GetMaxIndexAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetMaxAccountIndexResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetMaxAccountIndexResponseDto>> GetMaxIndexWithHttpInfoAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountSourceResponseDto</returns>
        System.Threading.Tasks.Task<GetAccountSourceResponseDto> GetSourceAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountSourceResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAccountSourceResponseDto>> GetSourceWithHttpInfoAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountSourceByAccountIdResponseDto</returns>
        System.Threading.Tasks.Task<GetAccountSourceByAccountIdResponseDto> GetSourceByAccountAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountSourceByAccountIdResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAccountSourceByAccountIdResponseDto>> GetSourceByAccountWithHttpInfoAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListAccountsResponseDto</returns>
        System.Threading.Tasks.Task<ListAccountsResponseDto> ListAccountsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListAccountsResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListAccountsResponseDto>> ListAccountsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListAccountAddressesResponseDto</returns>
        System.Threading.Tasks.Task<ListAccountAddressesResponseDto> ListAddressesAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListAccountAddressesResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListAccountAddressesResponseDto>> ListAddressesWithHttpInfoAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateAccountDisplayNameResponseDto</returns>
        System.Threading.Tasks.Task<UpdateAccountDisplayNameResponseDto> UpdateDisplayNameAsync(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateAccountDisplayNameResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateAccountDisplayNameResponseDto>> UpdateDisplayNameWithHttpInfoAsync(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IAccountApi : IAccountApiSync, IAccountApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal partial class AccountApi : IAccountApi
    {
        private KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi(string basePath)
        {
            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                new KyuzanInc.Peak.PublicApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountApi(KyuzanInc.Peak.PublicApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AccountApi(KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient client, KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient asyncClient, KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CreateAccountResponseDto</returns>
        public CreateAccountResponseDto CreateAccount(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CreateAccountResponseDto> localVarResponse = CreateAccountWithHttpInfo(createAccountRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CreateAccountResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CreateAccountResponseDto> CreateAccountWithHttpInfo(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'createAccountRequestDto' is set
            if (createAccountRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'createAccountRequestDto' when calling AccountApi->CreateAccount");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createAccountRequestDto;

            localVarRequestOptions.Operation = "AccountApi.CreateAccount";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateAccountResponseDto>("/public-api/v1/accounts/create", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAccount", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateAccountResponseDto</returns>
        public async System.Threading.Tasks.Task<CreateAccountResponseDto> CreateAccountAsync(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CreateAccountResponseDto> localVarResponse = await CreateAccountWithHttpInfoAsync(createAccountRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateAccountResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CreateAccountResponseDto>> CreateAccountWithHttpInfoAsync(CreateAccountRequestDto createAccountRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'createAccountRequestDto' is set
            if (createAccountRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'createAccountRequestDto' when calling AccountApi->CreateAccount");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createAccountRequestDto;

            localVarRequestOptions.Operation = "AccountApi.CreateAccount";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateAccountResponseDto>("/public-api/v1/accounts/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAccount", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountAddressWithAccountAndSourceResponseDto</returns>
        public GetAccountAddressWithAccountAndSourceResponseDto GetAddressDetail(string address, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountAddressWithAccountAndSourceResponseDto> localVarResponse = GetAddressDetailWithHttpInfo(address);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountAddressWithAccountAndSourceResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountAddressWithAccountAndSourceResponseDto> GetAddressDetailWithHttpInfo(string address, int operationIndex = 0)
        {
            // verify the required parameter 'address' is set
            if (address == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'address' when calling AccountApi->GetAddressDetail");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "address", address));

            localVarRequestOptions.Operation = "AccountApi.GetAddressDetail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetAccountAddressWithAccountAndSourceResponseDto>("/public-api/v1/accounts/get-address-detail", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAddressDetail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountAddressWithAccountAndSourceResponseDto</returns>
        public async System.Threading.Tasks.Task<GetAccountAddressWithAccountAndSourceResponseDto> GetAddressDetailAsync(string address, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountAddressWithAccountAndSourceResponseDto> localVarResponse = await GetAddressDetailWithHttpInfoAsync(address, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Account address</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountAddressWithAccountAndSourceResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountAddressWithAccountAndSourceResponseDto>> GetAddressDetailWithHttpInfoAsync(string address, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'address' is set
            if (address == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'address' when calling AccountApi->GetAddressDetail");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "address", address));

            localVarRequestOptions.Operation = "AccountApi.GetAddressDetail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAccountAddressWithAccountAndSourceResponseDto>("/public-api/v1/accounts/get-address-detail", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAddressDetail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetMaxAccountIndexResponseDto</returns>
        public GetMaxAccountIndexResponseDto GetMaxIndex(string accountSourceId, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMaxAccountIndexResponseDto> localVarResponse = GetMaxIndexWithHttpInfo(accountSourceId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetMaxAccountIndexResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMaxAccountIndexResponseDto> GetMaxIndexWithHttpInfo(string accountSourceId, int operationIndex = 0)
        {
            // verify the required parameter 'accountSourceId' is set
            if (accountSourceId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountSourceId' when calling AccountApi->GetMaxIndex");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountSourceId", accountSourceId));

            localVarRequestOptions.Operation = "AccountApi.GetMaxIndex";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetMaxAccountIndexResponseDto>("/public-api/v1/accounts/get-max-index", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMaxIndex", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetMaxAccountIndexResponseDto</returns>
        public async System.Threading.Tasks.Task<GetMaxAccountIndexResponseDto> GetMaxIndexAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMaxAccountIndexResponseDto> localVarResponse = await GetMaxIndexWithHttpInfoAsync(accountSourceId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetMaxAccountIndexResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMaxAccountIndexResponseDto>> GetMaxIndexWithHttpInfoAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'accountSourceId' is set
            if (accountSourceId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountSourceId' when calling AccountApi->GetMaxIndex");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountSourceId", accountSourceId));

            localVarRequestOptions.Operation = "AccountApi.GetMaxIndex";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetMaxAccountIndexResponseDto>("/public-api/v1/accounts/get-max-index", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMaxIndex", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountSourceResponseDto</returns>
        public GetAccountSourceResponseDto GetSource(string accountSourceId, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceResponseDto> localVarResponse = GetSourceWithHttpInfo(accountSourceId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountSourceResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceResponseDto> GetSourceWithHttpInfo(string accountSourceId, int operationIndex = 0)
        {
            // verify the required parameter 'accountSourceId' is set
            if (accountSourceId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountSourceId' when calling AccountApi->GetSource");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountSourceId", accountSourceId));

            localVarRequestOptions.Operation = "AccountApi.GetSource";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetAccountSourceResponseDto>("/public-api/v1/accounts/get-source", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSource", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountSourceResponseDto</returns>
        public async System.Threading.Tasks.Task<GetAccountSourceResponseDto> GetSourceAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceResponseDto> localVarResponse = await GetSourceWithHttpInfoAsync(accountSourceId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountSourceId">Account source ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountSourceResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceResponseDto>> GetSourceWithHttpInfoAsync(string accountSourceId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'accountSourceId' is set
            if (accountSourceId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountSourceId' when calling AccountApi->GetSource");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountSourceId", accountSourceId));

            localVarRequestOptions.Operation = "AccountApi.GetSource";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAccountSourceResponseDto>("/public-api/v1/accounts/get-source", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSource", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountSourceByAccountIdResponseDto</returns>
        public GetAccountSourceByAccountIdResponseDto GetSourceByAccount(string accountId, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceByAccountIdResponseDto> localVarResponse = GetSourceByAccountWithHttpInfo(accountId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountSourceByAccountIdResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceByAccountIdResponseDto> GetSourceByAccountWithHttpInfo(string accountId, int operationIndex = 0)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountId' when calling AccountApi->GetSourceByAccount");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountId", accountId));

            localVarRequestOptions.Operation = "AccountApi.GetSourceByAccount";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetAccountSourceByAccountIdResponseDto>("/public-api/v1/accounts/get-source-by-account", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSourceByAccount", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountSourceByAccountIdResponseDto</returns>
        public async System.Threading.Tasks.Task<GetAccountSourceByAccountIdResponseDto> GetSourceByAccountAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceByAccountIdResponseDto> localVarResponse = await GetSourceByAccountWithHttpInfoAsync(accountId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountSourceByAccountIdResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetAccountSourceByAccountIdResponseDto>> GetSourceByAccountWithHttpInfoAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountId' when calling AccountApi->GetSourceByAccount");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountId", accountId));

            localVarRequestOptions.Operation = "AccountApi.GetSourceByAccount";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAccountSourceByAccountIdResponseDto>("/public-api/v1/accounts/get-source-by-account", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSourceByAccount", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ListAccountsResponseDto</returns>
        public ListAccountsResponseDto ListAccounts(int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountsResponseDto> localVarResponse = ListAccountsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ListAccountsResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountsResponseDto> ListAccountsWithHttpInfo(int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AccountApi.ListAccounts";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListAccountsResponseDto>("/public-api/v1/accounts/list", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAccounts", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListAccountsResponseDto</returns>
        public async System.Threading.Tasks.Task<ListAccountsResponseDto> ListAccountsAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountsResponseDto> localVarResponse = await ListAccountsWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListAccountsResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountsResponseDto>> ListAccountsWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AccountApi.ListAccounts";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ListAccountsResponseDto>("/public-api/v1/accounts/list", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAccounts", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ListAccountAddressesResponseDto</returns>
        public ListAccountAddressesResponseDto ListAddresses(string accountId, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountAddressesResponseDto> localVarResponse = ListAddressesWithHttpInfo(accountId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ListAccountAddressesResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountAddressesResponseDto> ListAddressesWithHttpInfo(string accountId, int operationIndex = 0)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountId' when calling AccountApi->ListAddresses");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountId", accountId));

            localVarRequestOptions.Operation = "AccountApi.ListAddresses";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListAccountAddressesResponseDto>("/public-api/v1/accounts/list-addresses", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAddresses", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListAccountAddressesResponseDto</returns>
        public async System.Threading.Tasks.Task<ListAccountAddressesResponseDto> ListAddressesAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountAddressesResponseDto> localVarResponse = await ListAddressesWithHttpInfoAsync(accountId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListAccountAddressesResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ListAccountAddressesResponseDto>> ListAddressesWithHttpInfoAsync(string accountId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'accountId' when calling AccountApi->ListAddresses");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "accountId", accountId));

            localVarRequestOptions.Operation = "AccountApi.ListAddresses";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ListAccountAddressesResponseDto>("/public-api/v1/accounts/list-addresses", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAddresses", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateAccountDisplayNameResponseDto</returns>
        public UpdateAccountDisplayNameResponseDto UpdateDisplayName(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<UpdateAccountDisplayNameResponseDto> localVarResponse = UpdateDisplayNameWithHttpInfo(updateAccountDisplayNameRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateAccountDisplayNameResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<UpdateAccountDisplayNameResponseDto> UpdateDisplayNameWithHttpInfo(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'updateAccountDisplayNameRequestDto' is set
            if (updateAccountDisplayNameRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'updateAccountDisplayNameRequestDto' when calling AccountApi->UpdateDisplayName");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = updateAccountDisplayNameRequestDto;

            localVarRequestOptions.Operation = "AccountApi.UpdateDisplayName";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<UpdateAccountDisplayNameResponseDto>("/public-api/v1/accounts/update-display-name", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDisplayName", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateAccountDisplayNameResponseDto</returns>
        public async System.Threading.Tasks.Task<UpdateAccountDisplayNameResponseDto> UpdateDisplayNameAsync(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<UpdateAccountDisplayNameResponseDto> localVarResponse = await UpdateDisplayNameWithHttpInfoAsync(updateAccountDisplayNameRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updateAccountDisplayNameRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateAccountDisplayNameResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<UpdateAccountDisplayNameResponseDto>> UpdateDisplayNameWithHttpInfoAsync(UpdateAccountDisplayNameRequestDto updateAccountDisplayNameRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'updateAccountDisplayNameRequestDto' is set
            if (updateAccountDisplayNameRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'updateAccountDisplayNameRequestDto' when calling AccountApi->UpdateDisplayName");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = updateAccountDisplayNameRequestDto;

            localVarRequestOptions.Operation = "AccountApi.UpdateDisplayName";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UpdateAccountDisplayNameResponseDto>("/public-api/v1/accounts/update-display-name", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDisplayName", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
