/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using KyuzanInc.Peak.PublicApiClient.Client;
using KyuzanInc.Peak.PublicApiClient.Model;

namespace KyuzanInc.Peak.PublicApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Complete OTP Login
        /// </summary>
        /// <remarks>
        /// Completes OTP authentication by verifying the code and returning session token
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CompleteOtpLoginResponseDto</returns>
        CompleteOtpLoginResponseDto CompleteOtpLogin(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0);

        /// <summary>
        /// Complete OTP Login
        /// </summary>
        /// <remarks>
        /// Completes OTP authentication by verifying the code and returning session token
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CompleteOtpLoginResponseDto</returns>
        ApiResponse<CompleteOtpLoginResponseDto> CompleteOtpLoginWithHttpInfo(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0);
        /// <summary>
        /// Initialize OTP Login
        /// </summary>
        /// <remarks>
        /// Initializes OTP-based login by sending a one-time password to the user email
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InitOtpLoginResponseDto</returns>
        InitOtpLoginResponseDto InitOtpLogin(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0);

        /// <summary>
        /// Initialize OTP Login
        /// </summary>
        /// <remarks>
        /// Initializes OTP-based login by sending a one-time password to the user email
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InitOtpLoginResponseDto</returns>
        ApiResponse<InitOtpLoginResponseDto> InitOtpLoginWithHttpInfo(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0);
        /// <summary>
        /// Signup
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SignupResponseDto</returns>
        SignupResponseDto Signup(SignupRequestDto signupRequestDto, int operationIndex = 0);

        /// <summary>
        /// Signup
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SignupResponseDto</returns>
        ApiResponse<SignupResponseDto> SignupWithHttpInfo(SignupRequestDto signupRequestDto, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Complete OTP Login
        /// </summary>
        /// <remarks>
        /// Completes OTP authentication by verifying the code and returning session token
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompleteOtpLoginResponseDto</returns>
        System.Threading.Tasks.Task<CompleteOtpLoginResponseDto> CompleteOtpLoginAsync(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Complete OTP Login
        /// </summary>
        /// <remarks>
        /// Completes OTP authentication by verifying the code and returning session token
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompleteOtpLoginResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompleteOtpLoginResponseDto>> CompleteOtpLoginWithHttpInfoAsync(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Initialize OTP Login
        /// </summary>
        /// <remarks>
        /// Initializes OTP-based login by sending a one-time password to the user email
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InitOtpLoginResponseDto</returns>
        System.Threading.Tasks.Task<InitOtpLoginResponseDto> InitOtpLoginAsync(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Initialize OTP Login
        /// </summary>
        /// <remarks>
        /// Initializes OTP-based login by sending a one-time password to the user email
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InitOtpLoginResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<InitOtpLoginResponseDto>> InitOtpLoginWithHttpInfoAsync(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Signup
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SignupResponseDto</returns>
        System.Threading.Tasks.Task<SignupResponseDto> SignupAsync(SignupRequestDto signupRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Signup
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SignupResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<SignupResponseDto>> SignupWithHttpInfoAsync(SignupRequestDto signupRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApi : IAuthApiSync, IAuthApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthApi : IAuthApi
    {
        private KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi(string basePath)
        {
            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                new KyuzanInc.Peak.PublicApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthApi(KyuzanInc.Peak.PublicApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AuthApi(KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient client, KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient asyncClient, KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Complete OTP Login Completes OTP authentication by verifying the code and returning session token
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CompleteOtpLoginResponseDto</returns>
        public CompleteOtpLoginResponseDto CompleteOtpLogin(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteOtpLoginResponseDto> localVarResponse = CompleteOtpLoginWithHttpInfo(completeOtpLoginRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Complete OTP Login Completes OTP authentication by verifying the code and returning session token
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CompleteOtpLoginResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteOtpLoginResponseDto> CompleteOtpLoginWithHttpInfo(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'completeOtpLoginRequestDto' is set
            if (completeOtpLoginRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'completeOtpLoginRequestDto' when calling AuthApi->CompleteOtpLogin");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = completeOtpLoginRequestDto;

            localVarRequestOptions.Operation = "AuthApi.CompleteOtpLogin";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CompleteOtpLoginResponseDto>("/public-api/v1/auth/otp/complete-login", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CompleteOtpLogin", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Complete OTP Login Completes OTP authentication by verifying the code and returning session token
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompleteOtpLoginResponseDto</returns>
        public async System.Threading.Tasks.Task<CompleteOtpLoginResponseDto> CompleteOtpLoginAsync(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteOtpLoginResponseDto> localVarResponse = await CompleteOtpLoginWithHttpInfoAsync(completeOtpLoginRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Complete OTP Login Completes OTP authentication by verifying the code and returning session token
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompleteOtpLoginResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteOtpLoginResponseDto>> CompleteOtpLoginWithHttpInfoAsync(CompleteOtpLoginRequestDto completeOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'completeOtpLoginRequestDto' is set
            if (completeOtpLoginRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'completeOtpLoginRequestDto' when calling AuthApi->CompleteOtpLogin");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = completeOtpLoginRequestDto;

            localVarRequestOptions.Operation = "AuthApi.CompleteOtpLogin";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CompleteOtpLoginResponseDto>("/public-api/v1/auth/otp/complete-login", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CompleteOtpLogin", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initialize OTP Login Initializes OTP-based login by sending a one-time password to the user email
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InitOtpLoginResponseDto</returns>
        public InitOtpLoginResponseDto InitOtpLogin(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitOtpLoginResponseDto> localVarResponse = InitOtpLoginWithHttpInfo(initOtpLoginRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Initialize OTP Login Initializes OTP-based login by sending a one-time password to the user email
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InitOtpLoginResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitOtpLoginResponseDto> InitOtpLoginWithHttpInfo(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'initOtpLoginRequestDto' is set
            if (initOtpLoginRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'initOtpLoginRequestDto' when calling AuthApi->InitOtpLogin");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = initOtpLoginRequestDto;

            localVarRequestOptions.Operation = "AuthApi.InitOtpLogin";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<InitOtpLoginResponseDto>("/public-api/v1/auth/otp/init-login", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("InitOtpLogin", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Initialize OTP Login Initializes OTP-based login by sending a one-time password to the user email
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InitOtpLoginResponseDto</returns>
        public async System.Threading.Tasks.Task<InitOtpLoginResponseDto> InitOtpLoginAsync(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitOtpLoginResponseDto> localVarResponse = await InitOtpLoginWithHttpInfoAsync(initOtpLoginRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Initialize OTP Login Initializes OTP-based login by sending a one-time password to the user email
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initOtpLoginRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InitOtpLoginResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitOtpLoginResponseDto>> InitOtpLoginWithHttpInfoAsync(InitOtpLoginRequestDto initOtpLoginRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'initOtpLoginRequestDto' is set
            if (initOtpLoginRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'initOtpLoginRequestDto' when calling AuthApi->InitOtpLogin");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = initOtpLoginRequestDto;

            localVarRequestOptions.Operation = "AuthApi.InitOtpLogin";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<InitOtpLoginResponseDto>("/public-api/v1/auth/otp/init-login", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("InitOtpLogin", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Signup 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SignupResponseDto</returns>
        public SignupResponseDto Signup(SignupRequestDto signupRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SignupResponseDto> localVarResponse = SignupWithHttpInfo(signupRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Signup 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SignupResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SignupResponseDto> SignupWithHttpInfo(SignupRequestDto signupRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'signupRequestDto' is set
            if (signupRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'signupRequestDto' when calling AuthApi->Signup");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = signupRequestDto;

            localVarRequestOptions.Operation = "AuthApi.Signup";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SignupResponseDto>("/public-api/v1/auth/signup", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Signup", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Signup 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SignupResponseDto</returns>
        public async System.Threading.Tasks.Task<SignupResponseDto> SignupAsync(SignupRequestDto signupRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SignupResponseDto> localVarResponse = await SignupWithHttpInfoAsync(signupRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Signup 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signupRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SignupResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SignupResponseDto>> SignupWithHttpInfoAsync(SignupRequestDto signupRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'signupRequestDto' is set
            if (signupRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'signupRequestDto' when calling AuthApi->Signup");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = signupRequestDto;

            localVarRequestOptions.Operation = "AuthApi.Signup";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SignupResponseDto>("/public-api/v1/auth/signup", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Signup", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
