/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using KyuzanInc.Peak.PublicApiClient.Client;
using KyuzanInc.Peak.PublicApiClient.Model;

namespace KyuzanInc.Peak.PublicApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMessagesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Sign a Bitcoin message
        /// </summary>
        /// <remarks>
        /// Signs a Bitcoin message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BitcoinSignMessageResponseDto</returns>
        BitcoinSignMessageResponseDto BitcoinSignMessage(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0);

        /// <summary>
        /// Sign a Bitcoin message
        /// </summary>
        /// <remarks>
        /// Signs a Bitcoin message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BitcoinSignMessageResponseDto</returns>
        ApiResponse<BitcoinSignMessageResponseDto> BitcoinSignMessageWithHttpInfo(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0);
        /// <summary>
        /// Sign an EVM message
        /// </summary>
        /// <remarks>
        /// Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EvmSignMessageResponseDto</returns>
        EvmSignMessageResponseDto EvmSignMessage(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0);

        /// <summary>
        /// Sign an EVM message
        /// </summary>
        /// <remarks>
        /// Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EvmSignMessageResponseDto</returns>
        ApiResponse<EvmSignMessageResponseDto> EvmSignMessageWithHttpInfo(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0);
        /// <summary>
        /// Sign a Solana message
        /// </summary>
        /// <remarks>
        /// Signs a Solana message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SolanaSignMessageResponseDto</returns>
        SolanaSignMessageResponseDto SolanaSignMessage(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0);

        /// <summary>
        /// Sign a Solana message
        /// </summary>
        /// <remarks>
        /// Signs a Solana message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SolanaSignMessageResponseDto</returns>
        ApiResponse<SolanaSignMessageResponseDto> SolanaSignMessageWithHttpInfo(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0);
        /// <summary>
        /// Sign a Sui message
        /// </summary>
        /// <remarks>
        /// Signs a Sui message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SuiSignMessageResponseDto</returns>
        SuiSignMessageResponseDto SuiSignMessage(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0);

        /// <summary>
        /// Sign a Sui message
        /// </summary>
        /// <remarks>
        /// Signs a Sui message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SuiSignMessageResponseDto</returns>
        ApiResponse<SuiSignMessageResponseDto> SuiSignMessageWithHttpInfo(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMessagesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Sign a Bitcoin message
        /// </summary>
        /// <remarks>
        /// Signs a Bitcoin message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BitcoinSignMessageResponseDto</returns>
        System.Threading.Tasks.Task<BitcoinSignMessageResponseDto> BitcoinSignMessageAsync(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Sign a Bitcoin message
        /// </summary>
        /// <remarks>
        /// Signs a Bitcoin message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BitcoinSignMessageResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<BitcoinSignMessageResponseDto>> BitcoinSignMessageWithHttpInfoAsync(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Sign an EVM message
        /// </summary>
        /// <remarks>
        /// Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EvmSignMessageResponseDto</returns>
        System.Threading.Tasks.Task<EvmSignMessageResponseDto> EvmSignMessageAsync(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Sign an EVM message
        /// </summary>
        /// <remarks>
        /// Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EvmSignMessageResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<EvmSignMessageResponseDto>> EvmSignMessageWithHttpInfoAsync(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Sign a Solana message
        /// </summary>
        /// <remarks>
        /// Signs a Solana message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SolanaSignMessageResponseDto</returns>
        System.Threading.Tasks.Task<SolanaSignMessageResponseDto> SolanaSignMessageAsync(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Sign a Solana message
        /// </summary>
        /// <remarks>
        /// Signs a Solana message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SolanaSignMessageResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<SolanaSignMessageResponseDto>> SolanaSignMessageWithHttpInfoAsync(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Sign a Sui message
        /// </summary>
        /// <remarks>
        /// Signs a Sui message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SuiSignMessageResponseDto</returns>
        System.Threading.Tasks.Task<SuiSignMessageResponseDto> SuiSignMessageAsync(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Sign a Sui message
        /// </summary>
        /// <remarks>
        /// Signs a Sui message using Turnkey and returns the signature
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SuiSignMessageResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuiSignMessageResponseDto>> SuiSignMessageWithHttpInfoAsync(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMessagesApi : IMessagesApiSync, IMessagesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MessagesApi : IMessagesApi
    {
        private KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MessagesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MessagesApi(string basePath)
        {
            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                new KyuzanInc.Peak.PublicApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MessagesApi(KyuzanInc.Peak.PublicApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MessagesApi(KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient client, KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient asyncClient, KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Sign a Bitcoin message Signs a Bitcoin message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BitcoinSignMessageResponseDto</returns>
        public BitcoinSignMessageResponseDto BitcoinSignMessage(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<BitcoinSignMessageResponseDto> localVarResponse = BitcoinSignMessageWithHttpInfo(bitcoinSignMessageRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign a Bitcoin message Signs a Bitcoin message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BitcoinSignMessageResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<BitcoinSignMessageResponseDto> BitcoinSignMessageWithHttpInfo(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'bitcoinSignMessageRequestDto' is set
            if (bitcoinSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'bitcoinSignMessageRequestDto' when calling MessagesApi->BitcoinSignMessage");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = bitcoinSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.BitcoinSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BitcoinSignMessageResponseDto>("/public-api/v1/message/bitcoin/sign", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BitcoinSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign a Bitcoin message Signs a Bitcoin message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BitcoinSignMessageResponseDto</returns>
        public async System.Threading.Tasks.Task<BitcoinSignMessageResponseDto> BitcoinSignMessageAsync(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<BitcoinSignMessageResponseDto> localVarResponse = await BitcoinSignMessageWithHttpInfoAsync(bitcoinSignMessageRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign a Bitcoin message Signs a Bitcoin message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bitcoinSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BitcoinSignMessageResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<BitcoinSignMessageResponseDto>> BitcoinSignMessageWithHttpInfoAsync(BitcoinSignMessageRequestDto bitcoinSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'bitcoinSignMessageRequestDto' is set
            if (bitcoinSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'bitcoinSignMessageRequestDto' when calling MessagesApi->BitcoinSignMessage");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = bitcoinSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.BitcoinSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BitcoinSignMessageResponseDto>("/public-api/v1/message/bitcoin/sign", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BitcoinSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign an EVM message Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EvmSignMessageResponseDto</returns>
        public EvmSignMessageResponseDto EvmSignMessage(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<EvmSignMessageResponseDto> localVarResponse = EvmSignMessageWithHttpInfo(evmSignMessageRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign an EVM message Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EvmSignMessageResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<EvmSignMessageResponseDto> EvmSignMessageWithHttpInfo(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'evmSignMessageRequestDto' is set
            if (evmSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'evmSignMessageRequestDto' when calling MessagesApi->EvmSignMessage");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = evmSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.EvmSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<EvmSignMessageResponseDto>("/public-api/v1/message/evm/sign", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EvmSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign an EVM message Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EvmSignMessageResponseDto</returns>
        public async System.Threading.Tasks.Task<EvmSignMessageResponseDto> EvmSignMessageAsync(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<EvmSignMessageResponseDto> localVarResponse = await EvmSignMessageWithHttpInfoAsync(evmSignMessageRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign an EVM message Signs an EVM message (personal_sign, eth_signTypedData, EIP-7702 authorization) using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evmSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EvmSignMessageResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<EvmSignMessageResponseDto>> EvmSignMessageWithHttpInfoAsync(EvmSignMessageRequestDto evmSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'evmSignMessageRequestDto' is set
            if (evmSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'evmSignMessageRequestDto' when calling MessagesApi->EvmSignMessage");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = evmSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.EvmSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<EvmSignMessageResponseDto>("/public-api/v1/message/evm/sign", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EvmSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign a Solana message Signs a Solana message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SolanaSignMessageResponseDto</returns>
        public SolanaSignMessageResponseDto SolanaSignMessage(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SolanaSignMessageResponseDto> localVarResponse = SolanaSignMessageWithHttpInfo(solanaSignMessageRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign a Solana message Signs a Solana message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SolanaSignMessageResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SolanaSignMessageResponseDto> SolanaSignMessageWithHttpInfo(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'solanaSignMessageRequestDto' is set
            if (solanaSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'solanaSignMessageRequestDto' when calling MessagesApi->SolanaSignMessage");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = solanaSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.SolanaSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SolanaSignMessageResponseDto>("/public-api/v1/message/solana/sign", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SolanaSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign a Solana message Signs a Solana message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SolanaSignMessageResponseDto</returns>
        public async System.Threading.Tasks.Task<SolanaSignMessageResponseDto> SolanaSignMessageAsync(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SolanaSignMessageResponseDto> localVarResponse = await SolanaSignMessageWithHttpInfoAsync(solanaSignMessageRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign a Solana message Signs a Solana message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="solanaSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SolanaSignMessageResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SolanaSignMessageResponseDto>> SolanaSignMessageWithHttpInfoAsync(SolanaSignMessageRequestDto solanaSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'solanaSignMessageRequestDto' is set
            if (solanaSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'solanaSignMessageRequestDto' when calling MessagesApi->SolanaSignMessage");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = solanaSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.SolanaSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SolanaSignMessageResponseDto>("/public-api/v1/message/solana/sign", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SolanaSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign a Sui message Signs a Sui message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SuiSignMessageResponseDto</returns>
        public SuiSignMessageResponseDto SuiSignMessage(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SuiSignMessageResponseDto> localVarResponse = SuiSignMessageWithHttpInfo(suiSignMessageRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign a Sui message Signs a Sui message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SuiSignMessageResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SuiSignMessageResponseDto> SuiSignMessageWithHttpInfo(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'suiSignMessageRequestDto' is set
            if (suiSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'suiSignMessageRequestDto' when calling MessagesApi->SuiSignMessage");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = suiSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.SuiSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SuiSignMessageResponseDto>("/public-api/v1/message/sui/sign", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SuiSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sign a Sui message Signs a Sui message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SuiSignMessageResponseDto</returns>
        public async System.Threading.Tasks.Task<SuiSignMessageResponseDto> SuiSignMessageAsync(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SuiSignMessageResponseDto> localVarResponse = await SuiSignMessageWithHttpInfoAsync(suiSignMessageRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sign a Sui message Signs a Sui message using Turnkey and returns the signature
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="suiSignMessageRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SuiSignMessageResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<SuiSignMessageResponseDto>> SuiSignMessageWithHttpInfoAsync(SuiSignMessageRequestDto suiSignMessageRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'suiSignMessageRequestDto' is set
            if (suiSignMessageRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'suiSignMessageRequestDto' when calling MessagesApi->SuiSignMessage");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = suiSignMessageRequestDto;

            localVarRequestOptions.Operation = "MessagesApi.SuiSignMessage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SuiSignMessageResponseDto>("/public-api/v1/message/sui/sign", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SuiSignMessage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
