/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using KyuzanInc.Peak.PublicApiClient.Client;
using KyuzanInc.Peak.PublicApiClient.Model;

namespace KyuzanInc.Peak.PublicApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecoveryPhraseApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CompleteImportRecoveryPhraseResponseDto</returns>
        CompleteImportRecoveryPhraseResponseDto CompleteImportRecoveryPhrase(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CompleteImportRecoveryPhraseResponseDto</returns>
        ApiResponse<CompleteImportRecoveryPhraseResponseDto> CompleteImportRecoveryPhraseWithHttpInfo(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExportRecoveryPhraseResponseDto</returns>
        ExportRecoveryPhraseResponseDto ExportRecoveryPhrase(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExportRecoveryPhraseResponseDto</returns>
        ApiResponse<ExportRecoveryPhraseResponseDto> ExportRecoveryPhraseWithHttpInfo(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InitImportRecoveryPhraseResponseDto</returns>
        InitImportRecoveryPhraseResponseDto InitImportRecoveryPhrase(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InitImportRecoveryPhraseResponseDto</returns>
        ApiResponse<InitImportRecoveryPhraseResponseDto> InitImportRecoveryPhraseWithHttpInfo(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecoveryPhraseApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompleteImportRecoveryPhraseResponseDto</returns>
        System.Threading.Tasks.Task<CompleteImportRecoveryPhraseResponseDto> CompleteImportRecoveryPhraseAsync(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompleteImportRecoveryPhraseResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompleteImportRecoveryPhraseResponseDto>> CompleteImportRecoveryPhraseWithHttpInfoAsync(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExportRecoveryPhraseResponseDto</returns>
        System.Threading.Tasks.Task<ExportRecoveryPhraseResponseDto> ExportRecoveryPhraseAsync(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExportRecoveryPhraseResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExportRecoveryPhraseResponseDto>> ExportRecoveryPhraseWithHttpInfoAsync(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InitImportRecoveryPhraseResponseDto</returns>
        System.Threading.Tasks.Task<InitImportRecoveryPhraseResponseDto> InitImportRecoveryPhraseAsync(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InitImportRecoveryPhraseResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<InitImportRecoveryPhraseResponseDto>> InitImportRecoveryPhraseWithHttpInfoAsync(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecoveryPhraseApi : IRecoveryPhraseApiSync, IRecoveryPhraseApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RecoveryPhraseApi : IRecoveryPhraseApi
    {
        private KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RecoveryPhraseApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecoveryPhraseApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecoveryPhraseApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecoveryPhraseApi(string basePath)
        {
            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                new KyuzanInc.Peak.PublicApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecoveryPhraseApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RecoveryPhraseApi(KyuzanInc.Peak.PublicApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecoveryPhraseApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RecoveryPhraseApi(KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient client, KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient asyncClient, KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CompleteImportRecoveryPhraseResponseDto</returns>
        public CompleteImportRecoveryPhraseResponseDto CompleteImportRecoveryPhrase(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteImportRecoveryPhraseResponseDto> localVarResponse = CompleteImportRecoveryPhraseWithHttpInfo(completeImportRecoveryPhraseRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CompleteImportRecoveryPhraseResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteImportRecoveryPhraseResponseDto> CompleteImportRecoveryPhraseWithHttpInfo(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'completeImportRecoveryPhraseRequestDto' is set
            if (completeImportRecoveryPhraseRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'completeImportRecoveryPhraseRequestDto' when calling RecoveryPhraseApi->CompleteImportRecoveryPhrase");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = completeImportRecoveryPhraseRequestDto;

            localVarRequestOptions.Operation = "RecoveryPhraseApi.CompleteImportRecoveryPhrase";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CompleteImportRecoveryPhraseResponseDto>("/public-api/v1/recovery-phrases/complete-import", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CompleteImportRecoveryPhrase", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompleteImportRecoveryPhraseResponseDto</returns>
        public async System.Threading.Tasks.Task<CompleteImportRecoveryPhraseResponseDto> CompleteImportRecoveryPhraseAsync(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteImportRecoveryPhraseResponseDto> localVarResponse = await CompleteImportRecoveryPhraseWithHttpInfoAsync(completeImportRecoveryPhraseRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="completeImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompleteImportRecoveryPhraseResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<CompleteImportRecoveryPhraseResponseDto>> CompleteImportRecoveryPhraseWithHttpInfoAsync(CompleteImportRecoveryPhraseRequestDto completeImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'completeImportRecoveryPhraseRequestDto' is set
            if (completeImportRecoveryPhraseRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'completeImportRecoveryPhraseRequestDto' when calling RecoveryPhraseApi->CompleteImportRecoveryPhrase");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = completeImportRecoveryPhraseRequestDto;

            localVarRequestOptions.Operation = "RecoveryPhraseApi.CompleteImportRecoveryPhrase";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CompleteImportRecoveryPhraseResponseDto>("/public-api/v1/recovery-phrases/complete-import", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CompleteImportRecoveryPhrase", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExportRecoveryPhraseResponseDto</returns>
        public ExportRecoveryPhraseResponseDto ExportRecoveryPhrase(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ExportRecoveryPhraseResponseDto> localVarResponse = ExportRecoveryPhraseWithHttpInfo(exportRecoveryPhraseRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExportRecoveryPhraseResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ExportRecoveryPhraseResponseDto> ExportRecoveryPhraseWithHttpInfo(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'exportRecoveryPhraseRequestDto' is set
            if (exportRecoveryPhraseRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'exportRecoveryPhraseRequestDto' when calling RecoveryPhraseApi->ExportRecoveryPhrase");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = exportRecoveryPhraseRequestDto;

            localVarRequestOptions.Operation = "RecoveryPhraseApi.ExportRecoveryPhrase";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ExportRecoveryPhraseResponseDto>("/public-api/v1/recovery-phrases/export", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExportRecoveryPhrase", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExportRecoveryPhraseResponseDto</returns>
        public async System.Threading.Tasks.Task<ExportRecoveryPhraseResponseDto> ExportRecoveryPhraseAsync(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ExportRecoveryPhraseResponseDto> localVarResponse = await ExportRecoveryPhraseWithHttpInfoAsync(exportRecoveryPhraseRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExportRecoveryPhraseResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<ExportRecoveryPhraseResponseDto>> ExportRecoveryPhraseWithHttpInfoAsync(ExportRecoveryPhraseRequestDto exportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'exportRecoveryPhraseRequestDto' is set
            if (exportRecoveryPhraseRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'exportRecoveryPhraseRequestDto' when calling RecoveryPhraseApi->ExportRecoveryPhrase");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = exportRecoveryPhraseRequestDto;

            localVarRequestOptions.Operation = "RecoveryPhraseApi.ExportRecoveryPhrase";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ExportRecoveryPhraseResponseDto>("/public-api/v1/recovery-phrases/export", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExportRecoveryPhrase", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InitImportRecoveryPhraseResponseDto</returns>
        public InitImportRecoveryPhraseResponseDto InitImportRecoveryPhrase(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitImportRecoveryPhraseResponseDto> localVarResponse = InitImportRecoveryPhraseWithHttpInfo(initImportRecoveryPhraseRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InitImportRecoveryPhraseResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitImportRecoveryPhraseResponseDto> InitImportRecoveryPhraseWithHttpInfo(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'initImportRecoveryPhraseRequestDto' is set
            if (initImportRecoveryPhraseRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'initImportRecoveryPhraseRequestDto' when calling RecoveryPhraseApi->InitImportRecoveryPhrase");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = initImportRecoveryPhraseRequestDto;

            localVarRequestOptions.Operation = "RecoveryPhraseApi.InitImportRecoveryPhrase";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<InitImportRecoveryPhraseResponseDto>("/public-api/v1/recovery-phrases/init-import", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("InitImportRecoveryPhrase", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InitImportRecoveryPhraseResponseDto</returns>
        public async System.Threading.Tasks.Task<InitImportRecoveryPhraseResponseDto> InitImportRecoveryPhraseAsync(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitImportRecoveryPhraseResponseDto> localVarResponse = await InitImportRecoveryPhraseWithHttpInfoAsync(initImportRecoveryPhraseRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="initImportRecoveryPhraseRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InitImportRecoveryPhraseResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<InitImportRecoveryPhraseResponseDto>> InitImportRecoveryPhraseWithHttpInfoAsync(InitImportRecoveryPhraseRequestDto initImportRecoveryPhraseRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'initImportRecoveryPhraseRequestDto' is set
            if (initImportRecoveryPhraseRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'initImportRecoveryPhraseRequestDto' when calling RecoveryPhraseApi->InitImportRecoveryPhrase");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = initImportRecoveryPhraseRequestDto;

            localVarRequestOptions.Operation = "RecoveryPhraseApi.InitImportRecoveryPhrase";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<InitImportRecoveryPhraseResponseDto>("/public-api/v1/recovery-phrases/init-import", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("InitImportRecoveryPhrase", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
