/*
 * Peak Public API
 *
 * Peak Public API for Users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using KyuzanInc.Peak.PublicApiClient.Client;
using KyuzanInc.Peak.PublicApiClient.Model;

namespace KyuzanInc.Peak.PublicApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DeleteUserResponseDto</returns>
        DeleteUserResponseDto DeleteUser(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DeleteUserResponseDto</returns>
        ApiResponse<DeleteUserResponseDto> DeleteUserWithHttpInfo(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetMeResponseDto</returns>
        GetMeResponseDto GetMe(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetMeResponseDto</returns>
        ApiResponse<GetMeResponseDto> GetMeWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetUserResponseDto</returns>
        GetUserResponseDto GetUser(string email, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetUserResponseDto</returns>
        ApiResponse<GetUserResponseDto> GetUserWithHttpInfo(string email, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteUserResponseDto</returns>
        System.Threading.Tasks.Task<DeleteUserResponseDto> DeleteUserAsync(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteUserResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeleteUserResponseDto>> DeleteUserWithHttpInfoAsync(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetMeResponseDto</returns>
        System.Threading.Tasks.Task<GetMeResponseDto> GetMeAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetMeResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetMeResponseDto>> GetMeWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUserResponseDto</returns>
        System.Threading.Tasks.Task<GetUserResponseDto> GetUserAsync(string email, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUserResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetUserResponseDto>> GetUserWithHttpInfoAsync(string email, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserApi : IUserApiSync, IUserApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserApi : IUserApi
    {
        private KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserApi(string basePath)
        {
            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                new KyuzanInc.Peak.PublicApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserApi(KyuzanInc.Peak.PublicApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = KyuzanInc.Peak.PublicApiClient.Client.Configuration.MergeConfigurations(
                KyuzanInc.Peak.PublicApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new KyuzanInc.Peak.PublicApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UserApi(KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient client, KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient asyncClient, KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = KyuzanInc.Peak.PublicApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public KyuzanInc.Peak.PublicApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public KyuzanInc.Peak.PublicApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DeleteUserResponseDto</returns>
        public DeleteUserResponseDto DeleteUser(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<DeleteUserResponseDto> localVarResponse = DeleteUserWithHttpInfo(deleteUserRequestDto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DeleteUserResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<DeleteUserResponseDto> DeleteUserWithHttpInfo(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0)
        {
            // verify the required parameter 'deleteUserRequestDto' is set
            if (deleteUserRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'deleteUserRequestDto' when calling UserApi->DeleteUser");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = deleteUserRequestDto;

            localVarRequestOptions.Operation = "UserApi.DeleteUser";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DeleteUserResponseDto>("/public-api/v1/user/delete", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteUser", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteUserResponseDto</returns>
        public async System.Threading.Tasks.Task<DeleteUserResponseDto> DeleteUserAsync(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<DeleteUserResponseDto> localVarResponse = await DeleteUserWithHttpInfoAsync(deleteUserRequestDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deleteUserRequestDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteUserResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<DeleteUserResponseDto>> DeleteUserWithHttpInfoAsync(DeleteUserRequestDto deleteUserRequestDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'deleteUserRequestDto' is set
            if (deleteUserRequestDto == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'deleteUserRequestDto' when calling UserApi->DeleteUser");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = deleteUserRequestDto;

            localVarRequestOptions.Operation = "UserApi.DeleteUser";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DeleteUserResponseDto>("/public-api/v1/user/delete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteUser", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetMeResponseDto</returns>
        public GetMeResponseDto GetMe(int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMeResponseDto> localVarResponse = GetMeWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetMeResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMeResponseDto> GetMeWithHttpInfo(int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "UserApi.GetMe";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetMeResponseDto>("/public-api/v1/user/me", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMe", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetMeResponseDto</returns>
        public async System.Threading.Tasks.Task<GetMeResponseDto> GetMeAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMeResponseDto> localVarResponse = await GetMeWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetMeResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetMeResponseDto>> GetMeWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "UserApi.GetMe";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (public-api-turnkey-session-jwt) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetMeResponseDto>("/public-api/v1/user/me", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMe", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetUserResponseDto</returns>
        public GetUserResponseDto GetUser(string email, int operationIndex = 0)
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetUserResponseDto> localVarResponse = GetUserWithHttpInfo(email);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetUserResponseDto</returns>
        public KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetUserResponseDto> GetUserWithHttpInfo(string email, int operationIndex = 0)
        {
            // verify the required parameter 'email' is set
            if (email == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'email' when calling UserApi->GetUser");
            }

            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "email", email));

            localVarRequestOptions.Operation = "UserApi.GetUser";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetUserResponseDto>("/public-api/v1/user/get", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUser", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUserResponseDto</returns>
        public async System.Threading.Tasks.Task<GetUserResponseDto> GetUserAsync(string email, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetUserResponseDto> localVarResponse = await GetUserWithHttpInfoAsync(email, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="KyuzanInc.Peak.PublicApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email of the user</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUserResponseDto)</returns>
        public async System.Threading.Tasks.Task<KyuzanInc.Peak.PublicApiClient.Client.ApiResponse<GetUserResponseDto>> GetUserWithHttpInfoAsync(string email, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'email' is set
            if (email == null)
            {
                throw new KyuzanInc.Peak.PublicApiClient.Client.ApiException(400, "Missing required parameter 'email' when calling UserApi->GetUser");
            }


            KyuzanInc.Peak.PublicApiClient.Client.RequestOptions localVarRequestOptions = new KyuzanInc.Peak.PublicApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(KyuzanInc.Peak.PublicApiClient.Client.ClientUtils.ParameterToMultiMap("", "email", email));

            localVarRequestOptions.Operation = "UserApi.GetUser";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (public-api-project-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetUserResponseDto>("/public-api/v1/user/get", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUser", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
